if (keyboard_check_pressed(vk_numpad1)) room_goto(Boss_Stage_1)
if (keyboard_check_pressed(vk_numpad2)) room_goto(Boss_Stage_2)
if (keyboard_check_pressed(vk_numpad3)) room_goto(Boss_Stage_3)
if (keyboard_check_pressed(vk_numpad4)) room_goto(Card_Room)
if (keyboard_check_pressed(vk_numpad5)) room_goto(Boss_Stage_4)
if (keyboard_check_pressed(vk_numpad6)) room_goto(Fail_Screen)